version: '3.4'

services:
  mydemoprojects.api:
    image: ${DOCKER_REGISTRY-}mydemoprojectsapi-latest1
    build:
      context: .
      dockerfile: MyDemoProjects.Api/Dockerfile
    ports:
      - "5000:5000"

    environment:
         - ASPNETCORE_ENVIRONMENT=Development
         - ASPNETCORE_URLS=http://+:5000
    #volumes:
     # - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro